import os

CHECKPOINT_PATH = 'results'

# when editing, don't forget to add the path to .gitignore file
DATASETS_ROOT = 'data'
NOISE_DATASET_PATH = os.path.join(DATASETS_ROOT, 'noise_dataset')
COMMAND_DATASET_PATH = os.path.join(DATASETS_ROOT, 'commands_dataset')
TRAINING_EXAMPLES_PATH = os.path.join(DATASETS_ROOT, 'training', 'examples')
TRAINING_LABELS_PATH = os.path.join(DATASETS_ROOT, 'training', 'labels')

TRIGGER_WORD = 'marvin'
EXAMPLE_DURATION = 12
EXAMPLE_SAMPLING_RATE = 16000
TRAINING_EXAMPLES_COUNT = 20000
MAX_POSITIVES_COUNT_IN_EXAMPLE = 4
MAX_NEGATIVES_COUNT_IN_EXAMPLE = 5

BATCH_SIZE = 256
FFT_SIZE = 400
FFT_WIN_LENGTH = 200
FFT_HOP_LENGTH = 100
CONV_IN_CHANNELS = FFT_SIZE // 2 + 1
CONV_OUT_CHANNELS = 196
CONV_KERNEL_SIZE = 15
CONV_STRIDE = 4
FIRST_GRU_HIDDEN_SIZE = 128
SECOND_GRU_HIDDEN_SIZE = 128

